--------------------------------------------------------------------------------
Makelog started: 2024-01-31 17:15:30
Working directory: /export/home/dor/cxu/innovation_projs/analysis/science_geo/fe_analysis/code
--------------------------------------------------------------------------------
External links successfully created!
*********************************************************
* Error with `run_stata`. Traceback can be found below. *
*********************************************************

Traceback (most recent call last):
  File "/export/home/dor/cxu/.local/lib/python3.9/site-packages/gslab_make/run_program.py", line 931, in run_stata
    exit_code, stderr = direct.execute_command(command)
  File "/export/home/dor/cxu/.local/lib/python3.9/site-packages/gslab_make/private/programdirective.py", line 128, in execute_command
    raise_from(CritError(error_message), None)
  File "/usr/local/app/rcs_bin/grid3/envs/rcs_2022.01/lib/python3.9/site-packages/future/utils/__init__.py", line 403, in raise_from
    exec(execstr, myglobals, mylocals)
  File "<string>", line 1, in <module>
gslab_make.private.exceptionclasses.CritError: 
ERROR! The following command cannot be executed by operating system.
  > stata-mp -e do \"/export/home/dor/cxu/innovation_projs/analysis/science_geo/fe_analysis/code/analysis\.do\"
This could be because the command may be misspecified or does not exist. For further detail, refer to the traceback below.
  > Traceback (most recent call last):
  >   File "/export/home/dor/cxu/.local/lib/python3.9/site-packages/gslab_make/private/programdirective.py", line 115, in execute_command
  >     stdout, stderr = process.communicate()
  >   File "/usr/local/app/rcs_bin/grid3/envs/rcs_2022.01/lib/python3.9/subprocess.py", line 1134, in communicate
  >     stdout, stderr = self._communicate(input, endtime, timeout)
  >   File "/usr/local/app/rcs_bin/grid3/envs/rcs_2022.01/lib/python3.9/subprocess.py", line 1979, in _communicate
  >     ready = selector.select(timeout)
  >   File "/usr/local/app/rcs_bin/grid3/envs/rcs_2022.01/lib/python3.9/selectors.py", line 416, in select
  >     fd_event_list = self._selector.poll(timeout)
  > KeyboardInterrupt

